ARCHITECTURE:
  N_LAYERS: 6
  MLP_DIM: 3072
  N_LAYERS: 12
  N_HEADS: 12
  DROP_PROB: 0.1
  IMG_ENC:
    IMG_SIZE: 224
    PATCH_SIZE: 16
    IMG_DIM: 768
  TEXT_ENC:
    MAX_LEN: 64
    TEXT_DIM: 768
