ARCHITECTURE:
  N_LAYERS: 6
  MLP_DIM: 3072
  N_LAYERS: 12
  N_HEADS: 12
  DROP_PROB: 0.1
  IMG_ENC:
    IMG_SIZE: 224
    PATCH_SIZE: 16
    IMG_DIM: 768
  TEXT_ENC:
    MAX_LEN: 64
    TEXT_DIM: 768
TRAINING:
  BATCH_SIZE: 32_768
  VOCAB_SIZE: 49_408
  LR: 
  N_EPOCHS: 32 # "We train all models for 32 epochs."
  N_TEMP: 100
  WEIGHT_DECAY: 0.2
  WARMUP_STEPS: 2000
OPTIMIZER:
  BETA1: 0.9
  BETA2: 0.98
  EPS: 1e-6
