SEED: 333
ARCHITECTURE:
  N_LAYERS: 6
  # MLP_DIM: 3072
  MLP_DIM: 768
  N_LAYERS: 12
  N_HEADS: 12
  DROP_PROB: 0.1
  IMG_ENC:
    IMG_SIZE: 224
    PATCH_SIZE: 16
    # IMG_DIM: 768
    IMG_DIM: 192
  TEXT_ENC:
    MAX_LEN: 64
    # TEXT_DIM: 768
    TEXT_DIM: 192
  EMBED_DIM: 192
TRAINING:
  VOCAB_SIZE: 49_408
  LR: 0.0002 # ?
  N_EPOCHS: 32 # "We train all models for 32 epochs."
  # N_TEMP: 100
  WARMUP_STEPS: 2000
OPTIMIZER:
  BETA1: 0.9
  BETA2: 0.98
  EPS: 0.000001
  WEIGHT_DECAY: 0.2
