wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.9.13
    cli_version: 0.15.12
    framework: huggingface
    huggingface_version: 4.29.0
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1697907873.65733
    t:
      1:
      - 1
      - 11
      - 41
      - 49
      - 55
      2:
      - 1
      - 11
      - 41
      - 49
      - 55
      3:
      - 23
      4: 3.9.13
      5: 0.15.12
      6: 4.29.0
      8:
      - 4
      - 5
      13: darwin-arm64
SEED:
  desc: null
  value: 333
ARCHITECTURE:
  desc: null
  value:
    N_LAYERS: 12
    MLP_DIM: 3072
    N_HEADS: 12
    DROP_PROB: 0.1
    IMG_ENC:
      IMG_SIZE: 224
      PATCH_SIZE: 16
      IMG_DIM: 768
    TEXT_ENC:
      MAX_LEN: 64
      TEXT_DIM: 768
TRAINING:
  desc: null
  value:
    VOCAB_SIZE: 49408
    LR: 0.0002
    N_EPOCHS: 32
    WARMUP_STEPS: 2000
OPTIMIZER:
  desc: null
  value:
    BETA1: 0.9
    BETA2: 0.98
    EPS: 1.0e-06
    WEIGHT_DECAY: 0.2
