SEED: 333
ARCHITECTURE:
  DROP_PROB: 0.1
  IMG_ENC:
    IMG_SIZE: 224
    PATCH_SIZE: 32
    N_LAYERS: 12
    N_HEADS: 12
    HIDDEN_DIM: 768
    MLP_DIM: 3072
  TEXT_ENC:
    VOCAB_SIZE: 30522
    N_LAYERS: 6
    N_HEADS: 12
    HIDDEN_DIM: 768
    MLP_DIM: 3072
  EMBED_DIM: 256
TRAINING:
  LR: 0.00009
OPTIMIZER:
  BETA1: 0.9
  BETA2: 0.98
  EPS: 0.000001
  WEIGHT_DECAY: 0.2
CIFAR100:
  N_CLASSES: 100
